### ISSUE TITLE
blocking whitelitsed websites

### ISSUE THREAD

**Issue by brettaus** [unindented/whitelist-manager#10] opened 2015-10-17 03:47 UTC
I have added the whitelist extension to chrome, I have added around 4 websites to the list, I also have bookmarks for the sites so I don't have to type them all the time.

When I click on the bookmark in chrome the website is blocked & I get a blank tab even though I have the site in the white list ?

**Comment by unindented** [comment] 2015-10-17 18:21
@brettaus can you post a screenshot of your whitelist configuration so that I can try and reproduce?

**Comment by unindented** [comment] 2016-03-22 14:32
I can't reproduce, so I'm closing this.

**Closed by unindented** 2016-03-22 14:32 UTC
